name = "Example pack 2"

[[commands]]
name = "print execution dir 2"
type = "script"
script = 'echo "$COMMAND_PACK_EXECUTION_DIR"'
alias = "print_execution_dir"
description = "print the execution path"

[[commands]]
name = "print config dir 2"
type = "script"
script = 'echo "$COMMAND_PACK_DIR"'
alias = "print_config_dir"
description = "print a directory of the config file"

[[commands]]
name = "print welcome message 2"
type = "script"
script = 'echo "one more $WELCOME_MESSAGE"'
alias = "print_welcome_message"
description = "print one more welcome message from the environment"
