name = "Example pack"

[[commands]]
name = "print execution dir"
type = "script"
script = 'echo "$COMMAND_PACK_EXECUTION_DIR"'
alias = "print_execution_dir"
description = "print the execution path"

[[commands]]
name = "print config dir"
type = "script"
script = 'echo "$COMMAND_PACK_DIR"'
alias = "print_config_dir"
description = "print a directory of the config file"

[[commands]]
name = "inlined pack"
type = "inlined_pack"
path = '$COMMAND_PACK_DIR/echoCommandPack.toml'

[commands.env]
WORD_2 = "WORLD"

[[commands]]
name = "inlined pack"
type = "inlined_pack"
path = '$COMMAND_PACK_DIR/build/buildCommandPack.toml'
alias_prefix = "build_"

[env]
WORD_1 = "HELLO"
