name = "Example pack"

[[commands]]
name = "print config dir"
type = "script"
script = 'echo "$COMMAND_PACK_DIR"'
alias = "print_config_dir"
description = "You can use the COMMAND_PACK_DIR environment variable to refer your config directory"

[[commands]]
name = "print execution dir"
type = "script"
script = 'echo "$COMMAND_PACK_EXECUTION_DIR"'
alias = "print_execution_dir"
description = "You can use the COMMAND_PACK_EXECUTION_DIR environment variable to refer to a directory from which the program is running"

[[commands]]
name = "inlined pack"
type = "inlined_pack"
path = '$COMMAND_PACK_DIR/echoCommandPack.toml'

[commands.env]
WORD_2 = "WORLD"

[[commands]]
name = "build tui pack"
type = "inlined_pack"
path = '$COMMAND_PACK_DIR/build/commandPack.toml'
name_prefix = "build tui pack: "
alias_prefix = "build_"

[env]
WORD_1 = "HELLO"
